AWSTemplateFormatVersion: 2010-09-09
Description: |
  This my Cfn template for EC2 with Security Group

Resources:
  MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04cb4ca688797756f
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroupIds: 
        - !Ref MySecGrp
      Tags: 
        - Key: Name
          Value: !Sub Erdi ${AWS::StackName}
      UserData:
        Fn::Base64: |
            #! /bin/bash
            yum update -y
            yum install httpd -y
            FOLDER="https://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@raw.githubusercontent.com/ErdiErkan/101-kittens-carousel-static-website-ec2/main/static-web"
            cd /var/www/html
            wget ${FOLDER}/index.html
            wget ${FOLDER}/cat0.jpg
            wget ${FOLDER}/cat1.jpg
            wget ${FOLDER}/cat2.jpg
            wget ${FOLDER}/cat3.png
            systemctl start httpd
            systemctl enable httpd

  MySecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh and http # Required
      GroupName: erdisecportfolio
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 80
        CidrIp: 0.0.0.0/0
      Tags:
      - Value: 
        Key: 
Outputs:
  WebSiteURL:
    Description: This output gives the URL of EC2
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyWebServer.PublicDnsName